include_guard(GLOBAL)

add_library(cuDNN::cuDNN SHARED IMPORTED GLOBAL)
if (WIN32)
    set(GENESIA_CUDNN_ROOT "C:/Program Files/NVIDIA/CUDNN/v9.24" CACHE PATH "Installed cuDNN SDK")
    find_path(GENESIA_CUDNN_INCLUDE_DIRECTORY cudnn.h
            PATHS "${GENESIA_CUDNN_ROOT}/include/13.3" NO_DEFAULT_PATH REQUIRED)
    find_library(GENESIA_CUDNN_LIBRARY cudnn
            PATHS "${GENESIA_CUDNN_ROOT}/lib/13.3/x64" NO_DEFAULT_PATH REQUIRED)
    find_file(GENESIA_CUDNN_DLL cudnn64_9.dll
            PATHS "${GENESIA_CUDNN_ROOT}/bin/13.3/x64" NO_DEFAULT_PATH REQUIRED)
    cmake_path(GET GENESIA_CUDNN_DLL PARENT_PATH GENESIA_CUDNN_DLL_DIRECTORY)
    file(GLOB GENESIA_CUDNN_DLLS "${GENESIA_CUDNN_DLL_DIRECTORY}/*.dll")
    set_target_properties(cuDNN::cuDNN PROPERTIES
            IMPORTED_IMPLIB "${GENESIA_CUDNN_LIBRARY}"
            IMPORTED_LOCATION "${GENESIA_CUDNN_DLL}")
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_path(GENESIA_CUDNN_INCLUDE_DIRECTORY cudnn.h REQUIRED)
    find_library(GENESIA_CUDNN_LIBRARY cudnn REQUIRED)
    set_target_properties(cuDNN::cuDNN PROPERTIES IMPORTED_LOCATION "${GENESIA_CUDNN_LIBRARY}")
endif ()

set_target_properties(cuDNN::cuDNN PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${GENESIA_CUDNN_INCLUDE_DIRECTORY}")
